# Pointing (central receives pointer data from peripheral)
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# BLE connection interval (7.5ms — minimum latency)
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

# Display (SSD1306 OLED)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n
CONFIG_LVGL_USE_THEME_MONO=y
