manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk_driver_azoteq
      url: https://github.com/stelmakhdigital/zmk_driver_azoteq
      revision: master
  self:
    path: config
